version = "0.6.0"
content_dir = "pages"

[[html.assets]]
css_stylesheet = "./style.css"

[pdf.spine]
title = "Rheo Manual"
exclude = ["404.typ"]

[epub.spine]
title = "Rheo Manual"
exclude = ["404.typ", "endmatter.typ", "frontmatter.typ"]
