#import "index.typ": sidebar-site
#show: sidebar-site.with(current: "format-html")

= HTML

Typst #link("https://typst.app/docs/reference/html/")[experimentally supports] HTML.
This means that not all Typst syntax will translate to a meaningful HTML structure.
The most common features in everyday prose are all supported, however, such as text markup, links, headings, footnotes, citations, and mathematics.
For more information on which features are currently supported in Typst's HTML export, refer to the #link("https://github.com/typst/typst/issues/5512")[HTML export tracking issue].

Math is worth calling out on its own, because it's one of the areas where Typst's HTML export is already fully mature rather than experimental.
Both inline equations and display blocks compile straight to MathML, so an integral or a matrix keeps its own semantics in the DOM instead of becoming a rasterised image or a pile of hand-positioned `<span>`s.
Rheo does no translation work here itself; it just carries Typst's MathML through unchanged to both HTML and EPUB output.

== From one file to a whole site

Where the Typst CLI produces a single HTML file, Rheo turns your project into a static site.
Each Typst source file becomes its own HTML page, and #link(<relative-linking>)[relative links] between files are rewritten from `.typ` to `.html` so that navigation works in the browser.

Rheo also provides a development server with live reloading when you use the `watch` command, so you can see changes in the browser as you edit your source files:

```bash
rheo watch my-project --html --open
```

The HTML format supports configurable #link(<custom-js-css>)[CSS and JavaScript] entrypoints, as well as #link(<assets>)[asset copying] for additional files your site needs.
These entrypoints are also the mechanism through which reading augmentations can be delivered -- the #link("https://github.com/freecomputinglab/rheo/tree/main/examples/tooltip_html")[tooltip example], for instance, uses a custom Typst function and a JavaScript entrypoint to provide inline tooltips in the HTML output.#footnote[Note that there is an experimental #link("https://github.com/typst/typst/pull/7964")[bundle format] in upstream Typst which allows you to achieve similar results. We are tracking this closely, but for the time being have not incorporated this feature/format into Rheo on account of some critical deficiencies such as #link("https://github.com/typst/typst/issues/1097")[the inability to have multiple bibliographies in the same source file].]

You can customize which files are included in the HTML output using a #link(<spines>)[spine].
By default, Rheo compiles every Typst file under `content_dir`; to exclude certain files from the site, narrow it with `[html.spine] exclude`:

```toml
[html.spine]
exclude = ["drafts/**"]
```

Rheo sites can also carry #link("./atom-feeds.html")[a feed] --- Atom, RSS, or JSON Feed --- generated by the `@rheo/feeds` Typst package rather than a core config key.

Because each source file becomes its own page, Rheo resets the footnote counter to `1` at the start of every HTML page by default, so each page numbers its footnotes independently.
Set `reset_footnotes = false` under `[html]` to let footnotes accumulate continuously across the whole site instead:

```toml
[html]
reset_footnotes = false
```
